/*
 * 统一认证和授权系统
 * 更多信息请联系pphh
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pphh.oauth.client.api;

import com.pphh.oauth.client.ApiException;
import com.pphh.oauth.client.model.AuthCodeVO;
import com.pphh.oauth.client.model.ClientVO;
import com.pphh.oauth.client.model.OAuth2AccessToken;
import com.pphh.oauth.client.model.ValidityVO;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for Oauth2EndpointApi
 */
@Ignore
public class Oauth2EndpointApiTest {

    private final OAuth2EndpointApi api = new OAuth2EndpointApi();

    
    /**
     * OAuth2授权点
     *
     * 授权点颁发authorization code
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void authorizeUsingPOSTTest() throws ApiException {
        ClientVO clientVO = null;
        AuthCodeVO response = api.authorizeUsingPOST(clientVO);

        // TODO: test validations
    }
    
    /**
     * OAuth2令牌检查点
     *
     * 检查令牌
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void introspectTokenUsingPOSTTest() throws ApiException {
        String token = null;
        ValidityVO response = api.introspectTokenUsingPOST(token);

        // TODO: test validations
    }
    
    /**
     * OAuth2令牌颁发点
     *
     * 颁发令牌access/refresh token
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void issueTokenUsingPOST1Test() throws ApiException {
        String grantType = null;
        String authorization = null;
        String code = null;
        String redirectUri = null;
        String refreshToken = null;
        String username = null;
        String password = null;
        OAuth2AccessToken response = api.issueTokenUsingPOST(grantType, authorization, code, redirectUri, refreshToken, username, password);

        // TODO: test validations
    }
    
    /**
     * OAuth2令牌吊销点
     *
     * 吊销令牌
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void revokeTokenUsingPOSTTest() throws ApiException {
        String token = null;
        String authorization = null;
        Boolean response = api.revokeTokenUsingPOST(token, authorization);

        // TODO: test validations
    }
    
}
